export const characters = [
  {
    id: 1,
    name: "Rover",
    role: "The Protagonist",
    img: "/asset/characters/rover-aero.webp",
    desc: "A mysterious figure with a forgotten past. Able to wield Echoes and adapt to any battle.",
  },
  {
    id: 2,
    name: "Jinshi",
    role: "Wind Resonator",
    img: "/asset/characters/jinhsi.webp",
    desc: "Graceful and deadly, her wind-based skills offer mobility and elegance in battle.",
  },
  {
    id: 3,
    name: "Taoqi",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/taoqi.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 4,
    name: "Changli",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/changli.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 5,
    name: "Cantarella",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/cantarella.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 6,
    name: "Aalto",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/aalto.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 7,
    name: "Baizhi",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/baizhi.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 8,
    name: "Brant",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/brant.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 9,
    name: "Calcharo",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/calcharo.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 10,
    name: "Camellya",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/camellya.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 11,
    name: "Carlotta",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/carlotta.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 12,
    name: "Chixia",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/chixia.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 13,
    name: "Ciaccona",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/ciaccona.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 14,
    name: "Encore",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/encore.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 15,
    name: "jianxin",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/jianxin.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 16,
    name: "Jiyan",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/jiyan.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 17,
    name: "Lingyang",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/lingyang.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 18,
    name: "Lumi",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/lumi.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 19,
    name: "Lupa",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/lupa.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 20,
    name: "Mortefi",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/mortefi.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 21,
    name: "Phoebe",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/phoebe.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 22,
    name: "Phrolova",
    role: "Leader of the Midnight Rangers",
    img: "/asset/characters/phrolova.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
];

export const videos = [
  {
    src: "/asset/vidio/Jinshi-pv.mp4",
    thumb: "/asset/thumb/thumb-jinshi.jpg",
    name: "Jinshi",
  },
  {
    src: "/asset/vidio/Cartethyia.mp4",
    thumb: "/asset/thumb/thumb-cartethyia.jpg",
    name: "Cartethyia",
  },
  {
    src: "/asset/vidio/bg-jinshi-vidio.mp4",
    thumb: "/asset/thumb/thumb-jinshi.jpg",
    name: "Jinshi",
  },
  {
    src: "/asset/vidio/bg-shorkeeper-vidio.mp4",
    thumb: "/asset/thumb/thumb-shorkeeper.jpg",
    name: "Shorkeeper",
  },
  {
    src: "/asset/vidio/pv-charlotta.mp4",
    thumb: "/asset/thumb/thumb-charlotta.jpg",
    name: "Charlotta",
  },
];
