export const characters = [
  {
    id: 10,
    name: "Rover",
    resonance: ["havoc", "aero", "spectro"],
    img: "/asset/characters/rover-aero.webp",
    desc: "A mysterious figure with a forgotten past. Able to wield Echoes and adapt to any battle.",
  },
  {
    id: 20,
    name: "Jinshi",
    resonance: "spectro",
    role: "DPS",
    img: "/asset/characters/jinhsi.webp",
    desc: "Graceful and deadly, her wind-based skills offer mobility and elegance in battle.",
  },
  {
    id: 30,
    name: "Taoqi",
    resonance: "havoc",
    img: "/asset/characters/taoqi.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 40,
    name: "Changli",
    resonance: "fusion",
    img: "/asset/characters/changli.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 50,
    name: "Cantarella",
    resonance: "havoc",
    img: "/asset/characters/cantarella.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 60,
    name: "Aalto",
    resonance: "aero",
    img: "/asset/characters/aalto.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 70,
    name: "Baizhi",
    resonance: "glacio",
    img: "/asset/characters/baizhi.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 80,
    name: "Brant",
    resonance: "fusion",
    img: "/asset/characters/brant.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 90,
    name: "Calcharo",
    resonance: "electro",
    img: "/asset/characters/calcharo.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 100,
    name: "Camellya",
    resonance: "havoc",
    img: "/asset/characters/camellya.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 110,
    name: "Carlotta",
    resonance: "galcio",
    img: "/asset/characters/carlotta.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 120,
    name: "Chixia",
    resonance: "fusion",
    img: "/asset/characters/chixia.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 130,
    name: "Ciaccona",
    resonance: "aero",
    img: "/asset/characters/ciaccona.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 140,
    name: "Encore",
    resonance: "fusion",
    img: "/asset/characters/encore.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 150,
    name: "jianxin",
    resonance: "aero",
    img: "/asset/characters/jianxin.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 160,
    name: "Jiyan",
    resonance: "aero",
    img: "/asset/characters/jiyan.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 170,
    name: "Lingyang",
    resonance: "glacio",
    img: "/asset/characters/lingyang.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 180,
    name: "Lumi",
    resonance: "electro",
    img: "/asset/characters/lumi.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 190,
    name: "Lupa",
    resonance: "fusion",
    img: "/asset/characters/lupa.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 200,
    name: "Mortefi",
    resonance: "fusion",
    img: "/asset/characters/mortefi.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 210,
    name: "Phoebe",
    resonance: "spectro",
    img: "/asset/characters/phoebe.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 220,
    name: "Phrolova",
    resonance: "havoc",
    img: "/asset/characters/phrolova.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 230,
    name: "Roccia",
    resonance: "havoc",
    img: "/asset/characters/roccia.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 240,
    name: "Sanhua",
    resonance: "glacio",
    img: "/asset/characters/sanhua.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 250,
    name: "Shorekeeper",
    resonance: "spectro",
    img: "/asset/characters/shorekeeper.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 260,
    name: "Verina",
    resonance: "spectro",
    img: "/asset/characters/verina.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 270,
    name: "Xiangli Yao",
    resonance: "electro",
    img: "/asset/characters/xiangli-yao.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 280,
    name: "Yangyang",
    resonance: "aero",
    img: "/asset/characters/yangyang.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 290,
    name: "YinLin",
    resonance: "electro",
    img: "/asset/characters/yinlin.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 300,
    name: "Youhu",
    resonance: "glacio",
    img: "/asset/characters/youhu.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 310,
    name: "Yuanwu",
    resonance: "electro",
    img: "/asset/characters/yuanwu.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 320,
    name: "Zani",
    resonance: "spectro",
    img: "/asset/characters/zani.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
  {
    id: 330,
    name: "Zhezhi",
    resonance: "glacio",
    img: "/asset/characters/zhezhi.webp",
    desc: "A stoic warrior dedicated to protecting others. Masters heavy weapons and control.",
  },
];

export const resonanceIcons = [
  { name: "glacio", img: "/asset/resonance/glacio.webp" },
  { name: "fusion", img: "/asset/resonance/fusion.webp" },
  { name: "electro", img: "/asset/resonance/electro.webp" },
  { name: "havoc", img: "/asset/resonance/havoc.webp" },
  { name: "aero", img: "/asset/resonance/aero.webp" },
  { name: "spectro", img: "/asset/resonance/spectro.webp" },
];

export const videos = [
  {
    src: "/asset/vidio/Jinshi-pv.mp4",
    thumb: "/asset/thumb/thumb-jinshi.jpg",
    name: "Jinshi",
  },
  {
    src: "/asset/vidio/Cartethyia.mp4",
    thumb: "/asset/thumb/thumb-cartethyia.jpg",
    name: "Cartethyia",
  },
  {
    src: "/asset/vidio/bg-jinshi-vidio.mp4",
    thumb: "/asset/thumb/thumb-jinshi.jpg",
    name: "Jinshi",
  },
  {
    src: "/asset/vidio/bg-shorkeeper-vidio.mp4",
    thumb: "/asset/thumb/thumb-shorkeeper.jpg",
    name: "Shorkeeper",
  },
  {
    src: "/asset/vidio/pv-charlotta.mp4",
    thumb: "/asset/thumb/thumb-charlotta.jpg",
    name: "Charlotta",
  },
];
